version: "3.8"

services:
  # ğŸ‡ RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # cá»•ng dÃ¹ng cho app giao tiáº¿p
      - "15672:15672" # giao diá»‡n web quáº£n lÃ½ RabbitMQ
    networks:
      - micro_network

  # ğŸƒ MongoDB service
  mymongodb:
    image: mongo:7.0
    container_name: mymongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - micro_network

  # ğŸšª API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - order
      - product
    networks:
      - micro_network

  # ğŸ‘¤ Auth Service
  auth:
    build: ./auth
    env_file:
      - ./auth/.env
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - micro_network

  # ğŸ“¦ Product Service
  product:
    build: ./product
    env_file:
      - ./product/.env
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3001:3001"
    networks:
      - micro_network

  # ğŸ§¾ Order Service
  order:
    build: ./order
    env_file:
      - ./order/.env
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3002:3002"
    networks:
      - micro_network

volumes:
  mongo_data:

networks:
  micro_network:
    driver: bridge
